### ISSUE TITLE
Enhancement: Months or days mode

### ISSUE THREAD

**Issue by phlind** [cakechaser/obsidian-release-timeline#4] opened 2022-05-24 13:37 UTC
Would it be possible to make that work with months or even days (over several years)?

**Comment by cakechaser** [comment] 2022-05-25 14:04
It may take some time for me implement it, but so far I don't see why not!
I'll take a look when I have some time.

**Comment by cakechaser** [comment] 2022-08-31 12:26
@phlind, @AndrewKlay, @msnr, @nousernameavailableanymore, @ooker777,
Monthly timelines have been implemented in the latest release (via `release-timeline-month` codeblocks).
Would appreciate any feedback!

**Comment by AndrewKlay** [comment] 2022-08-31 15:33
@cakechaser Works and looks good for me, any plans to add "collapse" option for this variant in the future?
Noticed interesting behaviour with unrealistically big date gaps: timeline with "1993" and "10000" markings not only takes quite a long time to render (that's understandable), but for some reason it puts the "10000" before "1993" with ascended sorting and looks like this instead of expected format "year with months -> years between -> year with months":
![image](https://user-images.githubusercontent.com/22816298/187717378-b016dc3e-c977-486b-b30d-6ee47ceb1220.png)
Dates before 10000 (even 9999) working as intended with significantly faster rendering time. This 'issue' will be quite relevant 8000 years later, for now it's just an observation.

**Comment by nousernameavailableanymore** [comment] 2022-09-09 22:06
> @phlind, @AndrewKlay, @msnr, @nousernameavailableanymore, @ooker777, Monthly timelines have been implemented in the latest release (via `release-timeline-month` codeblocks). Would appreciate any feedback!

Looks good. Nice work 🙂

**Comment by rolandhesz** [comment] 2023-03-10 11:15
@cakechaser I like this plugin, and the monthly timelines are great!
 
Was wondering if adding weekly rendering could be done with a simple tweak of the monthly rendering.
I'm working on several projects and we have several releases over a month. It kind of works, but a nicer layout would be helpful
![image](https://user-images.githubusercontent.com/13273796/224300962-936de2be-7b62-4928-b61e-356329fb7317.png)

I started to tinker with it, but not sure I'm on the right track.

**Comment by cakechaser** [comment] 2023-03-12 17:08
@rolandhesz, I'm trying to understand what kind of layout would you like to see here.
Are the "03-10", "03-17".. part of note names or these would be week names in the new layout?

Just thinking, in case you just want to see the 4 notes from the screenshot for the March month, wouldn't the current monthly view be sufficient? Where you have 5 notes displayed for the month, sorted in the alphabetical order, with the release date in the beginning of each note name. This would also provide correct sorting time-wise.

Or do you want something more like this?
<img width="311" alt="image" src="https://user-images.githubusercontent.com/16690476/224560399-289a683f-0af5-41db-8882-8b0dae79e544.png">

**Comment by rolandhesz** [comment] 2023-03-13 17:24
@cakechaser 

The "03-10", "03-17" come from the `release date` field currently and this is how they show up. And ordering works with no issues.

As for the layout, I was thinking the same as the monthly is now, just "split" by week.
So,instead of having blocks of Mar, Apr, May, etc., the blocks would be the 03-06 (W10), 03-13 (W11), etc.
The advantage of that is that you can see the weeks when there is no release. So your second version with the image is what I was thinking of initially. Minus the month on the left, but having it there actually makes sense.

Your first option works too, where the releases are just laid out in a nicer way - I think the difference is just the lack of the visual guide for the weeks - and it already works, except for the layout, that needs some work - that is the easiest way to go, maybe needs a "weekly" flag and a CSS that makes it look nice.

But I was just trying to wrap my head around the code to see how I could make a weekly render, and work out which one works best and what the limitations are. 
It's 35% "I need this feature" and 65% "Let's mess with some Obsidian plugin code to practice".

**Comment by cakechaser** [comment] 2023-03-14 08:53
@rolandhesz, gotcha, thanks for the extended explanation!

I like the idea of seeing the weeks without releases, so I'll try some ideas to implement the weekly view.

**Comment by Rhydderch** [comment] 2023-05-16 10:32
I would love to have a weekly view as well! 
I would use it to show my weekly summaries so I can have a glance of my the past few weeks or even read a summary of my year by weeks :) (note, the weekly summary is saved to an inline dataview variable)

**Comment by cakechaser** [comment] 2023-05-16 11:10
@Rhydderch, thanks for the feedback!
I’m planning on implementing the weekly timeline in the near future.

**Comment by dxcore35** [comment] 2023-06-18 10:48
@cakechaser At least weeks will be amazing. I see huge benefit to add also weeks inside! Thank you. I will watch updates

**Comment by cakechaser** [comment] 2023-08-07 20:47
@rolandhesz @Rhydderch @dxcore35, I've just released an update with support for Weekly timelines.
Will close this issue, but let me know what you think!

**Closed by cakechaser** 2023-08-07 20:47 UTC

**Comment by rolandhesz** [comment] 2023-09-04 10:35
It looks great !  Sorry for being this slow, I wanted to respond two weeks ago.

![image](https://github.com/cakechaser/obsidian-release-timeline/assets/13273796/c5c5a9f4-864a-4fd1-a61c-f007eacb0c5b)

I have only one question: Is there a way to put some padding between timeline and the text?

**Comment by cakechaser** [comment] 2023-09-04 21:14
@rolandhesz, no worries, glad you like it!

That's strange, I see on your screenshot the timeline is not formatted properly.

This is how it should look like (tested on default theme + a couple of custom ones):
<img width="248" alt="image" src="https://github.com/cakechaser/obsidian-release-timeline/assets/16690476/386461b5-ee16-4872-87df-39748581a88f">


Which theme are you using?

And if you have any css snippets, could you try disabling them to see if you get the proper formatting again? Some custom code might be interfering with the timeline. If it's coming from the snippets, I can try to include more rules in the timeline css to work around them.

**Comment by rolandhesz** [comment] 2023-09-06 08:47
@cakechaser Hi, I've checked the theme and that seems to be the issue.

With the Minimal theme on:
![image](https://github.com/cakechaser/obsidian-release-timeline/assets/13273796/4a9435ad-86c5-401d-9d2f-7d835eabe2cd)

With the Default theme:
![image](https://github.com/cakechaser/obsidian-release-timeline/assets/13273796/52ead12c-9485-40e2-af81-a43208723a9c)

With the Github theme:
![image](https://github.com/cakechaser/obsidian-release-timeline/assets/13273796/63d6781e-4e11-4b14-966a-6f3e83e8e4c5)

I am not sure what is changed by the Minimal theme, but it seems to do something to get rid of that padding.

**Comment by cakechaser** [comment] 2023-09-06 19:22
@rolandhesz, thanks for checking, this looks like an easy fix, will release a new version within a couple of days.

**Comment by cakechaser** [comment] 2023-09-06 23:17
@rolandhesz, just published a new release with the fixes, please let me know if you still have any issues.
